### ISSUE TITLE
Start using a "jobs queue" (ie an OperationQueue) for processing tasks

### ISSUE THREAD

**Issue by sobri909** [sobri909/LocoKit#43]
With `MutableActivityType` coming soon (#34), there's going to potentially be a lot more background processing going on in LocoKit.

Arc App currently manages these job queue priorities, timeouts, etc by extensive use of duct tape, [number 8 wire](https://en.wikipedia.org/wiki/Number_8_wire), and spare hair ties found on the floor. That's not going to cut it once the queues are moved into LocoKit *[translation: It would be too embarrassing to have people see my jumble of hacks]*. So it's time to do it properly.

**Comment by sobri909** [comment]
Hunting through the energy reports further, it really does look like this is an iOS 12 bug. It is punishing multithreaded code on newer model devices that have more cores. Older phones are surviving fine because they've got less cores. 

iOS 12 shouldn't be punishing apps for running more efficiently on newer devices. There's no sense to that. So yeah, I smell an iOS bug. 

So perhaps I should be reporting this to Apple. Although I loathe going down the Radar sarlacc unless absolutely necessary. 

I'm also not able to clearly see the individual threads in Xcode's energy stack traces. It looks like it's showing the trace of a single thread, but ... it can't be. It's not possible to get 1200% CPU consumption from a single thread (or if it is, I will be very surprised), so there's definitely more to the story here that I'm going to have to piece together tomorrow. Sigh.

**Comment by sobri909** [comment]
## Goals

- Optimise for speed and parallelism in foreground
- All background tasks must be done at `.background` priority
- All background tasks must be done strictly in serial (parallelism will trigger the iOS 12 bug) 
- Ensure that current serial queues still have their serial nature enforced

## Todos

- [ ] Serial processing queue
- [ ] Parallel processing queue
- [ ] Parallel queue reduced to serial while in background
- [ ] Parallel queue suspended in background while serial queue not empty
- [ ] Pending operations on both queues reprioritised to `.background` on entering background

**Comment by sobri909** [comment]
I've merged this into `develop` now. It's proven stable in Arc 2.2.14 and 2.2.15.

There's a few more things I want to do with it, but they aren't urgent.
